// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AcessoDados.Implementacoes.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicio));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031716000_Inicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
